apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: merodeployment
  name: merodeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: merodeployment
  strategy: {}
  template:
    metadata:
      labels:
        app: merodeployment
    spec:
      initContainers:
      - name: init-myservice
        image: busybox
        command: ["sh","-c","echo initializing....... && sleep 5"]

      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
